// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription

#if canImport(AppleProductTypes)
import AppleProductTypes

let package = Package(
    name: "WizardlyCoding",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "WizardlyCoding",
            targets: ["AppModule"],
            bundleIdentifier: "com.sriganty.WizardlyCoding",
            teamIdentifier: "F7LL3A37L6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bandage),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Wizardly Coding uses the camera to detect surfaces and place AR content.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.v6]
)
#else
let package = Package(
    name: "WizardlyCoding",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .executable(
            name: "WizardlyCoding",
            targets: ["AppModule"]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.v6]
)
#endif
